name: Run Scripts Based on Condition

on:
  # schedule:
  #   - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script1:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "satyam-gaikwad"
        git config --global user.email "satyamgaikwad92@gmail.com"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run check_new_data_test.py and capture output
      id: check-new-data
      run: |
        python check_new_data_test.py
    
    - name: push and commit to repo
      id : push
      run: |
        git config --global user.name "satyam-gaikwad"
        git config --global user.email "satyamgaikwad92@gmail.com"
        git add results_test.txt parquet_files_test.txt
        git commit -m 'Update result and parquet files'
        git push

    - name: Read and update results_test.txt
      id: update-file
      run: |
        # Read the current content of results_test.txt
        content=$(cat results_test.txt)
        
        # Append some new content (modify as per your needs)
        new_content="${content}\nAdditional line added by workflow."
        
        # Write the updated content back to the file
        echo -e "$new_content" > results_test.txt
        
        # Verify the updated content
        cat results_test.txt

  run-script2:
    needs: run-script1
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run train_test.py
      run: |
        python train_test.py
