name: Run Scripts Based on Condition

on:
  # schedule:
  #   - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script1:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run check_new_data_test.py and capture output
      id: check-new-data
      run: |
        python check_new_data_test.py
        #echo "{result}:{result}" >> $GITHUB_OUTPUT  # Replace results_test.txt with your script1 output
    
    - name: push and commit to repo
      id : push
      run: |
        git config --global satyam-gaikwad 'github-actions'
        git config --global satyamgaikwad92@gmail.com 'github-actions@github.com'
        git add results_test.txt parquet_files_test.txt
        git commit -m 'Update result and parquet files'
        git push

  run-script2:
    needs: run-script1
    runs-on: ubuntu-latest
    if: ${{ needs.run-script1.outputs.result == '1' }}  # Adjust condition as per your script1 output

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run train_test.py
      run: |
        python train_test.py
